version: "3.6"
services:
  server:
    build:
      dockerfile: Dockerfile
      context: .
    image: heos-server
    network_mode: host
    # "host" network mode needed for device discovery: https://stackoverflow.com/questions/57899656/how-can-i-send-ssdp-traffic-to-network-from-a-docker-container
    # Therefore port fw should not be performed    vb
    #ports:
    #  - 5000:5000
    volumes:
      - /home/scoulomb/heospy/api-server/config:/working_dir/api-server/config
    # if those 3 variable are defined we will generate a config from those variables
    # This is very convenient when config file volume mapping is not possible (cf. QNAP NAS where not supported in compose file
    # When using in dev mode it implies a new discovery at every launch which can be painful, do not hesitate to comment
    environment:
      - CONF_PLAYER_NAME=Denon AVR-X2700H
      - CONF_USER=fake@gmail.com
      - CONF_PW=do-not-use-qwerty-as-your-password

